type News{
    _id: ID!
    title: String!
    description: String!
    author: User!
    active: Boolean!
}

input NewsInput{
    title: String!   
    description: String!
    author: ID!
    active: Boolean!
}

type Query{
    news: [News]!
    newsById(id: ID!): News!
}

type Mutation{
    createNews(data: NewsInput): News!
    updateNews(id: ID!, data: NewsInput): News!
    deleteNews(id: ID!): Boolean
    deleteNewsForAuthor(author: ID!): Boolean
}